### PR TITLE
Adds ability

### PR DESCRIPTION
**Pull request by Niiree**
Add spells for all dungeons

### CODE REVIEW

**Comment by amki** [comment]
Is this still WIP or ready to merge?

Thank you for helping ElitismHelper btw! :3

**Comment by Niiree** [comment]
If you can wait a bit.
I fix one problems. :)

**Comment by Niiree** [comment]
@amki It's good for me

**Comment by amki** [comment]
Merged it, should be released on curse as alpha in a few minutes. I'v been burned by patches before so I'm gonna test this a little while and wait for feedback before I make a release for people on the release channel.

Thank you for doing all this dirty work <3

If you have anything else don't hesitate to open a pull or issue. :3

**Comment by dominikmank** [comment]
playing with it already. works fine so far :P

**Comment by amki** [comment]
What I noticed: A lot of your spell IDs are wrong. The spell the mob casts and the spell that actually damages you are not always the same unfortunately. For example: [322473] = 20,		-- Plague Crash (Environement Margrave Stradama). The spell you actually take damage from is https://www.warcraftlogs.com/reports/6VBQ1qv8R2FpfTba/#fight=last&type=damage-taken&ability=322475 322475.

I know it's really unfortunate but there is no way to tell except looking up what actually damaged you.

I fixed some of the IDs already in https://github.com/amki/ElitismHelper/commit/8f19f7a30313bd74fc6c63ca54673c2cb0d09f07 (and removed some stuff that you actually HAVE to take, there is currently no way to determine if someone else had to take it and you were just cleaved)

**Comment by Niiree** [comment]
I saw this after a long evening of mm + and spent a few hours going through my logs to correct the ids.

https://www.warcraftlogs.com/reports/gdaThDkcC3mRpxKA

You were way too quick to correct.  I would have to push this tonight.

**Pull request merged**
