### PR TITLE
The War Within Season 1

### PR DESCRIPTION
**Pull request by Tribunate**
This contains all new TWW dungeons as well as the returning dungeons for S1.

As always, it probably still contains some minor inaccuracies or mistakes, but it should be good to go for release and I will update it accordingly.

### CODE REVIEW

**Comment by Tribunate** [comment]
Updated after more testing on retail

**Comment by adamderuwe** [comment]
> Updated after more testing on retail

Maybe release your own fork?  This repo is def dead.

**Comment by amki** [comment]
Which is funny because I just started playing WoW again.

I'm not that up to date on m+ yet though.

Am 5. September 2024 23:10:08 MESZ schrieb adamderuwe ***@***.***>:
>> Updated after more testing on retail
>
>Maybe release your own fork?  This repo is def dead.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/amki/ElitismHelper/pull/72#issuecomment-2332634705
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Everything not saved will be lost. - Nintendo Quit Screen Message

**Comment by amki** [comment]
@Tribunate is this ready to merge?

**Comment by Tribunate** [comment]
Yes, this should be good to go.

**Comment by amki** [comment]
Thank you very much!

**Pull request merged**
