### PR TITLE
Season 4 updates

### PR DESCRIPTION
**Pull request by ntowle**
Supports Tazavesh and the S4 affix.

### CODE REVIEW

**Comment by ntowle** [comment]
Hey @amki, any chance for a review? Thanks!

**Comment by amki** [comment]
I can't really test this right now because I 
don't have a sub but I'll merge it if you are ready.

I guess the people who set their updater to alpha will help test...

**Comment by ntowle** [comment]
@amki Yes the Tazavesh + Affix stuff is ready to merge. Thanks!

There are 6 "new" dungeons in Season 4 however, that will take me some time to come up with a full list of avoidable damage but I'll open another PR when that is ready.

**Comment by amki** [comment]
Thank you for your contribution then!

Maybe if S4 makes m+ worthwhile again I'll come back and do some more background work :3

**Pull request merged**
